### PR TITLE
Remove Jetifier

### PR DESCRIPTION
**Pull request by 0nko**
This PR replaces the Tenor library dependency reference with a jetified AAR version.

**To test:**
Verify the library and the sample app can be built and that the GIF search works when running the sample app (you'll need an API key)

### CODE REVIEW

**Review by ParaskP7 — APPROVED** [review]
👋 @0nko !

This is great, I just reviewed and tested the PR, everything looks good to me. I also double-checked with `Bye bye Jetifier` and it was successful, thank you! 🚀 🎉 🍾

> To test:
> Verify the library and the sample app can be built and that the GIF search works when running the sample app (you'll need an API key)

Btw, I tested the sample app, with an without an API key, and to my suprise both builds was working when I tried to search for a GIF even when having `<ADD API KEY HERE>` as the `TENOR_API_KEY` key... 🤷 😅 🤔

**Comment by ParaskP7** [comment]
👋 @0nko !

It is still a 👍 🟢 from my side, maybe @malinajirka wants to take a look as well, so I am letting you two merge this PR.

PS: About the Lint issue that you fixed by updating the outdated dependencies, in my [other PR here](https://github.com/wordpress-mobile/WordPress-MediaPicker-Android/pull/55), I actually didn't do the update, but instead suppressed the `GradleDependency` rule for the sample app (see 0605a8c6d72975e59d727f182a971dca5c0635fb commit). I did that because IMHO I think Lint shouldn't fail due to an outdated dependency, I believe it is too much of an expectation. 🤔

**Comment by 0nko** [comment]
Thanks, @ParaskP7!

> Btw, I tested the sample app, with an without an API key, and to my suprise both builds was working when I tried to search for a GIF even when having <ADD API KEY HERE> as the TENOR_API_KEY

Huh, that's weird 😆 

> About the Lint issue that you fixed by updating the outdated dependencies, in my https://github.com/wordpress-mobile/WordPress-MediaPicker-Android/pull/55, I actually didn't do the update, but instead suppressed the GradleDependency rule for the sample app (see https://github.com/wordpress-mobile/WordPress-MediaPicker-Android/commit/0605a8c6d72975e59d727f182a971dca5c0635fb commit). I did that because IMHO I think Lint shouldn't fail due to an outdated dependency, I believe it is too much of an expectation

Yeah.. But here it's not as much of a problem since it's much simpler to check if any of the flows might get broken by an update. So I'd say let's keep the newer versions. But I'll think about suppressing the errors next time.

**Comment by ParaskP7** [comment]
👋 @0nko !

> Huh, that's weird 😆

😅 

> Yeah.. But here it's not as much of a problem since it's much simpler to check if any of the flows might get broken by an update. So I'd say let's keep the newer versions. But I'll think about suppressing the errors next time.

True! 👍 

PS: Let me merge this now in order to progress with this `Jetifier` work and my in-progress `Gradle & AGP` upgrades, thank you! 🚀

**Pull request merged**
